apiVersion: 1

datasources:
  - name: BigQuery
    type: grafana-bigquery-datasource
    access: proxy
    isDefault: true
    editable: true
    jsonData:
      authenticationType: gce
      defaultProject: dataproject3

