name: Validate Python and Docker

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-python-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest

      - name: Lint Python code
        run: |
          flake8 . --max-line-length=120

      - name: Run Python tests
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build -t test-image:latest .
